language: node_js
node_js:
  - "7.1.0"
  - "node"
  - "6"
  - "5"
env:
  - CXX=g++-4.8
before_install:
  - "sudo apt-get install libavahi-compat-libdnssd-dev"
  - "mkdir ~/.homebridge"
before_script:
  - npm install -g eslint
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
